steps:
  - label: "CUDA Julia v1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - lib
    commands:
      - julia .ci/develop.jl
      - julia .ci/test.jl
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      KERNELABSTRACTIONS_TEST_BACKEND: "CUDA"
    timeout_in_minutes: 60

  - label: "CUDA Julia 1.7"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.7"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - lib
    commands:
      - julia .ci/develop.jl
      - julia .ci/test.jl
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      KERNELABSTRACTIONS_TEST_BACKEND: "CUDA"
    timeout_in_minutes: 60

  - label: "CUDA Julia nightly"
    plugins:
      - JuliaCI/julia#v1:
          version: "nightly"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - lib
    commands:
      - julia .ci/develop.jl
      - julia .ci/test.jl
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      KERNELABSTRACTIONS_TEST_BACKEND: "CUDA"
    timeout_in_minutes: 60

  - label: "ROCm Julia 1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - lib
    commands:
      - julia .ci/develop.jl
      - julia .ci/test.jl
    agents:
      queue: "juliagpu"
      rocm: "*"
    env:
      KERNELABSTRACTIONS_TEST_BACKEND: "ROCM"
    timeout_in_minutes: 60

  - label: "ROCm Julia 1.7"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.7"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - lib
    commands:
      - julia .ci/develop.jl
      - julia .ci/test.jl
    agents:
      queue: "juliagpu"
      rocm: "*"
    env:
      KERNELABSTRACTIONS_TEST_BACKEND: "ROCM"
    timeout_in_minutes: 60

  - label: "ROCm Julia nightly"
    plugins:
      - JuliaCI/julia#v1:
          version: "nightly"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - lib
    commands:
      - julia .ci/develop.jl
      - julia .ci/test.jl
    agents:
      queue: "juliagpu"
      rocm: "*"
    env:
      KERNELABSTRACTIONS_TEST_BACKEND: "ROCM"
    timeout_in_minutes: 60

  - label: "oneAPI Julia 1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - lib
    commands:
      - julia .ci/develop.jl
      - julia .ci/test.jl
    agents:
      queue: "juliagpu"
      intel: "*"
    env:
      KERNELABSTRACTIONS_TEST_BACKEND: "oneAPI"
    timeout_in_minutes: 60

  - label: "oneAPI Julia 1.7"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.7"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - lib
    commands:
      - julia .ci/develop.jl
      - julia .ci/test.jl
    agents:
      queue: "juliagpu"
      intel: "*"
    env:
      KERNELABSTRACTIONS_TEST_BACKEND: "oneAPI"
    timeout_in_minutes: 60
    
  - label: "Metal Julia 1.8"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.8"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - lib
    commands:
      - julia .ci/develop.jl
      - julia .ci/test.jl
    agents:
      queue: "juliaecosystem"
      os: "macos"
      arch: "aarch64"
    env:
      KERNELABSTRACTIONS_TEST_BACKEND: "Metal"
    timeout_in_minutes: 60

  - label: "oneAPI Julia nightly"
    plugins:
      - JuliaCI/julia#v1:
          version: "nightly"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - lib
    commands:
      - julia .ci/develop.jl
      - julia .ci/test.jl
    agents:
      queue: "juliagpu"
      intel: "*"
    env:
      KERNELABSTRACTIONS_TEST_BACKEND: "oneAPI"
    timeout_in_minutes: 60


env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  SECRET_CODECOV_TOKEN: "c5pjPUwULD2L8ss0gRtjCPiagRlTQ11TdbZP6gIhTPeA/gN5w5/7JvDCg36UpKER6FXnQDeBGGkQafHiLdBaH/FWQ2B2VKErtBarIBJa2zWvKu8mYs9PJzw/qLGT2sMXI9kcao63H6/HAwbslJcY0a5Mg+SwM3M05XqSHgnrHMnbBXysKP6VzFEIX7uoyEKOnoWDj8rGJKFYLW2DBRtd6Yc23ESfFXPAqbS7sgXxwQHKzz20FMQBJUmbiDIzPlk3k2n2TvgAWQ0VNK0e4/UooMbULL3UjY4oaMOF0XpJAnWlmvGgy8gEnZKSVp3ieXy/Ubu7BWwH/BT59wDy6LuDxA==;U2FsdGVkX18Wil69f7qJYu6yU5iNx+Zq8akUcOp+McU1CR4Jw4QBsrUKIF4W4uK+/752FQo40BwFsfnIC8CJ/Q=="
