steps:
  - label: "CUDA Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.6"
          - "1.7"
          - "1.8"
          - "beta"
        cuda:
          - "vc/ka_transition"
    plugins:
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
    commands:
      - |
        echo "Setting up Julia"
        curl -fsSL https://install.julialang.org | sh -s -- --yes --default-channel "{{matrix.version}}"
      - |
        export PATH="/root/.juliaup/bin:${PATH}"
        julia +{{matrix.version}} -e 'using Pkg
                println("--- :julia: Instantiating project")
                Pkg.develop(; path=pwd())
                Pkg.add(; name="CUDA", rev="{{matrix.cuda}}")
                println("+++ :julia: Running tests")
                Pkg.test("CUDA"; coverage=true)'
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      KERNELABSTRACTIONS_TEST_BACKEND: "CUDA"
    timeout_in_minutes: 60

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  SECRET_CODECOV_TOKEN: "c5pjPUwULD2L8ss0gRtjCPiagRlTQ11TdbZP6gIhTPeA/gN5w5/7JvDCg36UpKER6FXnQDeBGGkQafHiLdBaH/FWQ2B2VKErtBarIBJa2zWvKu8mYs9PJzw/qLGT2sMXI9kcao63H6/HAwbslJcY0a5Mg+SwM3M05XqSHgnrHMnbBXysKP6VzFEIX7uoyEKOnoWDj8rGJKFYLW2DBRtd6Yc23ESfFXPAqbS7sgXxwQHKzz20FMQBJUmbiDIzPlk3k2n2TvgAWQ0VNK0e4/UooMbULL3UjY4oaMOF0XpJAnWlmvGgy8gEnZKSVp3ieXy/Ubu7BWwH/BT59wDy6LuDxA==;U2FsdGVkX18Wil69f7qJYu6yU5iNx+Zq8akUcOp+McU1CR4Jw4QBsrUKIF4W4uK+/752FQo40BwFsfnIC8CJ/Q=="
