steps:
  - label: "Julia v1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    commands:
      - julia --project=test -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))'
      - julia --project=test -e 'using Pkg; Pkg.develop(PackageSpec(path=joinpath(pwd(),"lib","CUDAKernels")))'
      - julia -e 'using Pkg; Pkg.add(name="Run", version="0.1")'
      - julia -e 'using Run; Run.prepare_test()'
      - julia -e 'using Run; Run.test()'
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60

  - label: "Julia 1.6-nightly"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.6-nightly"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    commands:
      - julia --project=test -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))'
      - julia --project=test -e 'using Pkg; Pkg.develop(PackageSpec(path=joinpath(pwd(),"lib","CUDAKernels")))'
      - julia -e 'using Pkg; Pkg.add(name="Run", version="0.1")'
      - julia -e 'using Run; Run.prepare_test()'
      - julia -e 'using Run; Run.test()'
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60

  - label: "Julia nightly"
    plugins:
      - JuliaCI/julia#v1:
          version: "nightly"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    commands:
      - julia --project=test -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))'
      - julia --project=test -e 'using Pkg; Pkg.develop(PackageSpec(path=joinpath(pwd(),"lib","CUDAKernels")))'
      - julia -e 'using Pkg; Pkg.add(name="Run", version="0.1")'
      - julia -e 'using Run; Run.prepare_test()'
      - julia -e 'using Run; Run.test()'
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  SECRET_CODECOV_TOKEN: "c5pjPUwULD2L8ss0gRtjCPiagRlTQ11TdbZP6gIhTPeA/gN5w5/7JvDCg36UpKER6FXnQDeBGGkQafHiLdBaH/FWQ2B2VKErtBarIBJa2zWvKu8mYs9PJzw/qLGT2sMXI9kcao63H6/HAwbslJcY0a5Mg+SwM3M05XqSHgnrHMnbBXysKP6VzFEIX7uoyEKOnoWDj8rGJKFYLW2DBRtd6Yc23ESfFXPAqbS7sgXxwQHKzz20FMQBJUmbiDIzPlk3k2n2TvgAWQ0VNK0e4/UooMbULL3UjY4oaMOF0XpJAnWlmvGgy8gEnZKSVp3ieXy/Ubu7BWwH/BT59wDy6LuDxA==;U2FsdGVkX18Wil69f7qJYu6yU5iNx+Zq8akUcOp+McU1CR4Jw4QBsrUKIF4W4uK+/752FQo40BwFsfnIC8CJ/Q=="
