steps:
  - label: "Julia 1.5"
    plugins:
      - JuliaCI/julia#v0.5:
          version: "1.5"
      - JuliaCI/julia-test#v0.3:
      # - JuliaCI/julia-coverage#v0.3:
      #     codecov: true
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60
    
  - label: "Julia 1.6-nightly"
    plugins:
      - JuliaCI/julia#v0.5:
          version: "1.6-nightly"
      - JuliaCI/julia-test#v0.3:
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60

  - label: "Julia nightly"
    plugins:
      - JuliaCI/julia#v0.5:
          version: "nightly"
      - JuliaCI/julia-test#v0.3:
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
