name = "oneAPIKernels"
uuid = "3b98bdbd-c5fb-40e4-a3b9-3b59ff234f62"
authors = ["Tim Besard <tim.besard@gmail.com>"]
version = "0.1.0"

[deps]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"

[compat]
oneAPI = "0.2.4"
KernelAbstractions = "0.8"
StaticArrays = "0.12, 1.0"
julia = "1.7"
