name: Benchmark a pull request

on:
  push:
    branches:
      - "main"
  # Run on pull requests
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
    generate_plots:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: julia-actions/setup-julia@v1
              with:
                version: "1"
            - uses: julia-actions/cache@v1
            - name: Install ValgrindBenchmarkTools
              env:
                JULIA_PKG_PRECOMPILE_AUTO: false
              run: |
                julia -e 'import Pkg; Pkg.add(url="https://github.com/JuliaCI/BenchmarkTools.jl", rev="vc/extendable")'
                julia -e 'import Pkg; Pkg.add(url="https://github.com/JuliaPerf/Valgrind.jl", rev="vc/bt")'
                julia -e 'import Pkg; Pkg.add(url="https://github.com/JuliaPerf/Valgrind.jl", rev="vc/bt", subdir="lib/ValgrindBenchmarkTools")'
            - name: Precompile
              env: 
                JULIA_CPU_TARGET: "haswell" # CPU emulated by Valgrind
              run: |
                julia -e 'import Pkg; Pkg.precompile()'
                julia --project=. -e 'import Pkg; Pkg.precompile()'
            - name: Add ~/.julia/bin to PATH
              run: |
                echo "$HOME/.julia/bin" >> $GITHUB_PATH
            - name: Run benchmarks
              uses: CodSpeedHQ/action@v3
              env:
                ENABLE_JITPROFILING: 1
              with:
                token: ${{ secrets.CODSPEED_TOKEN }}
                run: 'julia --project=. -L benchmark/benchmarks.jl -e "run(SUITE, \"\")"'
