name: Benchmark a pull request

on:
  pull_request:

permissions:
  # pull-requests: write
  contents: write
  deployments: write

jobs:
    generate_plots:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: julia-actions/setup-julia@v1
              with:
                version: "1"
            - uses: julia-actions/cache@v1
            - name: Extract Package Name from Project.toml
              id: extract-package-name
              run: |
                PACKAGE_NAME=$(grep "^name" Project.toml | sed 's/^name = "\(.*\)"$/\1/')
                echo "::set-output name=package_name::$PACKAGE_NAME"
            - name: Build AirspeedVelocity
              env:
                JULIA_NUM_THREADS: 2
              run: |
                # Lightweight build step, as sometimes the runner runs out of memory:
                julia -e 'ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0; import Pkg; Pkg.add("AirspeedVelocity")'
                julia -e 'ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0; import Pkg; Pkg.build("AirspeedVelocity")'
            - name: Add ~/.julia/bin to PATH
              run: |
                echo "$HOME/.julia/bin" >> $GITHUB_PATH
            - name: Run benchmarks
              run: |
                echo $PATH
                ls -l ~/.julia/bin
                mkdir results
                benchpkg ${{ steps.extract-package-name.outputs.package_name }} --rev="${{github.event.pull_request.head.sha}}" --url=${{ github.event.repository.clone_url }} --bench-on="${{github.event.repository.default_branch}}" --output-dir=results/ --tune
            - name: Store benchmark result
              uses: benchmark-action/github-action-benchmark@v1
              with:
                name: Julia benchmark result
                tool: 'julia'
                output-file-path: results/results_${{ steps.extract-package-name.outputs.package_name }}@${{github.event.pull_request.head.sha}}.json
                # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
                github-token: ${{ secrets.GITHUB_TOKEN }}
                auto-push: true
                # Show alert with commit comment on detecting possible performance regression
                alert-threshold: '150%'
                comment-on-alert: true
                fail-on-alert: true
                alert-comment-cc-users: '@vchuravy'
